[project]
name = "todo-pro-serverless-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["boto3>=1.38.6"]

[dependency-groups]
dev = ["ruff>=0.11.7"]
