FROM node:22-alpine

RUN mkdir -p /opt/app

# Set working directory
WORKDIR /opt/app

# Copy root package.json and lock file
COPY package*.json ./

# Install all dependencies
RUN npm install

COPY . .
