services:
  db:
    image: amazon/dynamodb-local:2.6.1
    ports:
      - '8000:8000'
  # db_setup:
  #   image: ghcr.io/astral-sh/uv:alpine
  #   volumes:
  #     - ./ops-tf/dev/py:/app
  #   working_dir: /app
  #   command: 'sh -c "uv sync && uv run src/dynamodb_local_dev.py -a setup"'
  #   depends_on:
  #     - db
