FROM node:22-alpine AS builder

RUN mkdir -p /opt/app
RUN mkdir -p /opt/artifact

# Set working directory
WORKDIR /opt/app

# Copy package files
COPY package*.json ./

# npm install
RUN npm i --no-audit --no-fund && npm cache clean --force

# Copy application code
COPY . .

# Run build
RUN npm run build -w apps/todo-pro-web

FROM node:22-alpine

RUN apk add --no-cache zip

RUN mkdir -p /opt/app
RUN mkdir -p /opt/artifact

# Set working directory
WORKDIR /opt/app

COPY --from=builder /opt/app/apps/todo-pro-web/dist ./dist

RUN mv dist/* /opt/app

RUN zip -r web_dist.zip ./*

CMD ["cp", "/opt/app/web_dist.zip", "/opt/artifact"]
